default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: radius_contractors_development

test:
  <<: *default
  database: radius_contractors_test

production:
  primary: &primary_production
    <<: *default
    database: radius_contractors_production
    username: radius_contractors
    password: <%= ENV["RADIUS_CONTRACTORS_DATABASE_PASSWORD"] %>
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    database: radius_contractors_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: radius_contractors_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: radius_contractors_production_cable
    migrations_paths: db/cable_migrate
